<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nn_address"
 *
 * Auto generated by Extension Builder 2014-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NN Address',
	'description' => 'Alternative to tt_address based on Typo3 6.x and extbase/fluid. For one contact you can add multiple addresses,mails,numbers and can extend fields with Flexform.',
	'category' => 'plugin',
	'author' => 'Hendrik Reimers (Neonaut GmbH)',
	'author_email' => 'info@neonaut.de',
	'author_company' => 'Neonaut GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0.0-6.2.99',
			'fluid' => '6.0.0-6.2.99',
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>